export const BOARDING = 'Boarding';
export const HOME = 'Home';
export const LOGIN = 'Login';
export const SIGNUP = 'Signup';
export const LOGOUT = 'Logout';
export const DASHBOARD = 'Dashboard';
export const RECENT_PRODUCTS = 'Recent Products';
export const ALL_PRODUCTS = 'All Products';
export const MANAGE_PRODUCT = 'Manage Products';
